[package]
name = "paimon-rust-dev"
version = "0.1.0"
edition = "2024"

[dependencies]
# 远程执行配置的容器地址.
#paimon = { path = "/share/paimon-rust/crates/paimon" }
# 本地跑时候的本地路径.
#paimon = { path = "/Users/john.wick/CLionProjects/share/paimon-rust/crates/paimon" }
# hunter 本地路径.
paimon = { path = "/Users/hunter/CLionProjects/share/paimon-rust/crates/paimon" }
arrow = "58.0"
arrow-array = { version = "58.0", features = ["ffi"] }
arrow-buffer = "58.0"
arrow-schema = "58.0"
arrow-cast = "58.0"
arrow-ord = "58.0"
arrow-select = "58.0"
datafusion = "53.0.0"
datafusion-ffi = "53.0.0"
parquet = "58.0"
futures = "0.3"

tokio = "1.39.2"
tokio-util = "0.7"
